### ISSUE TITLE
Improve betting validation for pass/dont_pass to avoid db updates in resolve_bets

### ISSUE THREAD

**Issue by tswift242** [Rymark1/DiscordBotInitial#11]
https://github.com/Rymark1/DiscordBotInitial/blob/30845584bd5b4d15e1ac3850f03602523e8387ea/lib/craps_support/crap_resolve.py#L19

This line seems like something that would be unnecessary if proper validation logic existed to prevent users from placing dont_pass bets if they already have a pass bet. And vice versa for https://github.com/Rymark1/DiscordBotInitial/blob/30845584bd5b4d15e1ac3850f03602523e8387ea/lib/craps_support/crap_resolve.py#L22

**Comment by Rymark1** [comment]
I'd love to live in a world where everyone always bets the pass line, however some jerks do exist.  Since I'm iterating through all the rows, its possible that someone could have bet the don't.

**Comment by tswift242** [comment]
But you're clearing the don't pass after resolving the pass, and vice versa. I don't understand that. Should line 19 clear the pass and line 22 clear the don't pass and they're backwards?

**Comment by Rymark1** [comment]
On a comeout roll, when a 7 is hit, the don't loses and we need to clear
that bet.  The pass line stays on and I don't update it.

When 2,3,12 are hit we clear the pass line and keep the don't up.

Since I don't know if the person has that bet, I just update that variable
to zero.
