### ISSUE TITLE
The point shouldn't be set in the db multiple times

### ISSUE THREAD

**Issue by tswift242** [Rymark1/DiscordBotInitial#12]
https://github.com/Rymark1/DiscordBotInitial/blob/30845584bd5b4d15e1ac3850f03602523e8387ea/lib/craps_support/crap_resolve.py#L24

Currently, the db update to set the point is embedded in the for loop, which means there are N identical db updates for a craps board with N users. This db update should happen once.

**Comment by Rymark1** [comment]
done.
