### ISSUE TITLE
SQL query improvent: in +shooter command, select only those records where i_pass != 0

### ISSUE THREAD

**Issue by tswift242** [Rymark1/DiscordBotInitial#7]
https://github.com/Rymark1/DiscordBotInitial/blob/30845584bd5b4d15e1ac3850f03602523e8387ea/lib/cogs/craps.py#L108

Instead of filtering out user records who don't have passline bets after the fact in code, filter via the SQL query by using the WHERE command.

**Comment by Rymark1** [comment]
done.
